Backend/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('login.urls', 'auth'), namespace='auth')),
    path('', include(('aplication.urls', 'app'), namespace='app')),
]

aplication/urls.py
from django.urls import path
from aplication.views import AppListView


urlpatterns = [
    path('', AppListView.as_view(), name="home"),
]

login/urls.py
from django.urls import path
from .views import LoginViewAuth, LogoutViewAuth, ListAllUserAuth, DetailUserAuth, EditUserAuth

urlpatterns = [
    path('login/', LoginViewAuth.as_view(), name="login" ),
    path('logout/', LogoutViewAuth.as_view(), name="logout" ),

    path('list/', ListAllUserAuth.as_view(), name="list" ),
    path('detail/<int:pk>/', DetailUserAuth.as_view(), name="detail" ),
    path('edit/<int:pk>/', EditUserAuth.as_view(), name="edit" ),

]

aplication/models.py
from django.db import models

# Create your models here.

class University(models.Model):
	name = models.CharField(max_length=50)

	class Meta:
		verbose_name = "University"
		verbose_name_plural = "Universitys"

	def __str__(self):
		return self.name

class Student(models.Model):
	name = models.CharField(max_length=50)
	university = models.ForeignKey(University, on_delete=models.CASCADE)

	class Meta:
		verbose_name = "Student"
		verbose_name_plural = "Students"

	def __str__(self):
		return self.name

    

login/models.py
from django.db import models

# Create your models here.

aplication/views.py
from django.shortcuts import render
from django.views.generic import ListView
from django.contrib.auth.mixins import LoginRequiredMixin

from aplication.models import Student

# Create your views here.


class AppListView(LoginRequiredMixin, ListView):
	login_url = '/login/'
	template_name = 'home.html'
	queryset = Student.objects.all()
	


		

login/views.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView,LogoutView
from django.views.generic import ListView, UpdateView, DetailView
from django.contrib.auth.mixins import LoginRequiredMixin
from .form import LoginForm, UpdateUserForm
from django.shortcuts import get_object_or_404
from django.http import Http404


class LoginViewAuth(LoginView):
	template_name = "login_page.html"
	form_class = LoginForm
	redirect_authenticated_user = True

class LogoutViewAuth(LogoutView):
	pass




class ListAllUserAuth(LoginRequiredMixin, ListView):
	template_name = "list_all_user.html"
	queryset = User.objects.all()

class DetailUserAuth(LoginRequiredMixin, DetailView):
	template_name = "detail_user.html"
	context_object_name = "detail_user_object" #rename context
	def get_object(self):
		pk = self.kwargs.get("pk") #pk sending by url
		user = self.request.user.pk #host connected
		if pk==user or self.request.user.is_superuser: #only the same can be edited OR if Administrator, else 404
			return get_object_or_404(User, pk=pk)
		raise Http404

class EditUserAuth(LoginRequiredMixin, UpdateView):
	template_name = "edit_user.html"
	form_class = UpdateUserForm

	def get_object(self):
		pk = self.kwargs.get('pk')
		user = self.request.user.pk #host connected
		if pk==user or self.request.user.is_superuser: #only the same can be edited OR if Administrator, else 404
			return get_object_or_404(User, pk=pk)
		raise Http404

	

aplication/templates/home.html
{% extends 'base.html' %} 
{% load static %} 




{% block content %}
	<h1>List View:</h1>
	<ol>
	{% for i in object_list %}
		<li>{{ i }} - Universidad {{i.university}} </li>
	{% endfor %}
	</ol>
	

{% endblock %}

login/templates/detail_user.html
{% extends 'base.html' %} 
{% load static %} 

{% block content %}
<h2>Detalle de Usuario</h2>

<div>
	<i class="fa fa-user" style="font-size: 200px" aria-hidden="true"></i>
</div>

<div>
	Nombre: {{detail_user_object.first_name}} {{detail_user_object.last_name}} <br>
	email: {{detail_user_object.email}} <br>
	<a href="{% url 'auth:edit' detail_user_object.pk %}">
		<i class="fa fa-pencil-square" style="font-size: 50px" aria-hidden="true"></i>
	</a>


</div>




{% endblock %}

login/templates/edit_user.html
{% extends 'base.html' %} 
{% load static %} 

{% block content %}
<form method="post">{% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Update">
</form>


{% endblock %}

login/templates/list_all_user.html
{% extends 'base.html' %} 
{% load static %} 

{% block content %}

<h2>Lista de Usuarios</h2>

<table>
  <tr>
    <th>ID Usuario</th>
    <th>Nombre</th>
    <th>Correo</th>
    <th>Editar</th>
    <th>Eliminar</th>
  </tr>
  {% for object in object_list %}
  	<tr>
  	  <th>
        {{ object.pk }}
        <a href="{% url 'auth:detail' object.pk %}"> 
          <i class="fa fa-eye" aria-hidden="true"></i>
        </a>
      </th>
      <th>{{ object.first_name }} {{ object.last_name }}</th>
      <th>{{ object.email }}</th>
      <th>
        <a href="{% url 'auth:edit' object.pk %}">
          <i class="fa fa-pencil-square" aria-hidden="true"></i>
        </a>
      </th>
      <th>
        <a href="#">
          <i class="fa fa-trash-o" style="color:red" aria-hidden="true"></i>
        </a>
      </th>

    </tr>
  {% endfor %}
</table>

{% endblock %}

login/templates/login_page.html
 {% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link href='https://fonts.googleapis.com/css?family=Open+Sans' rel='stylesheet' type='text/css'>
  <link href="{% static 'css/loginpage.css' %}" rel='stylesheet' type='text/css'>



  <title>Login</title>
</head>
<body>
  <input type="radio" checked id="toggle--login" name="toggle" class="ghost" />
  <input type="radio" id="toggle--signup" name="toggle" class="ghost" />

<form class="form form--login framed" method="post" action="{% url 'auth:login' %}">
{% csrf_token %}
 
    {{ form.username }}
    {{ form.password }}


<!--     <input type="email" placeholder="Email" class="input input--top" />
    <input type="password" placeholder="Password" class="input" /> -->
    <input type="submit" value="Log in" class="input input--submit" />
    
    <label for="toggle--signup" class="text text--small text--centered">New? <b>Sign up</b></label>
  </form>
  
  <form class="form form--signup framed">
    <h2 class="text text--centered text--omega">Join the other <b>152.6 million</b> blogs and</br>share all that you love.</h2>

    <input type="email" placeholder="Email" class="input input--top" />
    <input type="password" placeholder="Password" class="input" />
    <input type="text" placeholder="Username" class="input" />
    <input type="submit" value="Sign up" class="input input--submit" />
    
    <label for="toggle--login" class="text text--small text--centered">Not new? <b>Log in</b></label>
  </form>

<!--   <div class="legal">
    <a class="text text--small text--border-right" href="javascript:;">Terms</a>
    <a class="text text--small text--border-right" href="javascript:;">Privacy</a>
    <a class="text text--small" href="javascript:;">Password help</a>
  </div> -->

<!--   <div class="photo-cred">
    <a class="text text--small" title="Check out their blog." href="http://cabinporn.com/post/125371354365/the-cabin-book-book-in-the-wild-21-in-the-us" target="_blank">Photo posted by <b>cabinporn</b></a>
  </div> -->

  <div class="fullscreen-bg"></div>

  
</body>
</html>









  

templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
      <meta charset="UTF-8">
   <meta name="viewport" content="width=device-width, initial-scale=1">
   <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Ubuntu" type="text/css" />
   <link rel="stylesheet" href="{% static 'css/style.css' %}"" type="text/css" />
   <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" type="text/css" rel="stylesheet">
   

   <title>Home</title>
   
<body class="text-center bgimg">
  <nav class="navbar navbar-default navbar-fixed-top" style="padding-top:-20px;" role="navigation">
    <div class="container-fluid">
      <div class="navbar-header">

        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>>
                        <span class="sr-only"> Toggle Navigation </span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>

        <a class="navbar-brand" href="#"><span class="fa fa-terminal"></span></a>
      </div>

      <div id="navbar" class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
          <li><a href="{% url 'app:home' %}">Home <span class="sr-only">(current)</span></a></li>
          {% if request.user.is_superuser %}
            <li><a href="{% url 'auth:list' %}">Users Managements</a></li>
          {% else %}
            <li><a href="{% url 'auth:detail' request.user.pk %}">Account</a></li>
          {% endif %}
        </ul>

        <h5><a class="pull-right" href="{% url 'auth:logout' %}"><i class="fa fa-sign-out"></i>Salir</a></h5>
      </div>
    </div>
  </nav>

  <div class="container">
    <div style="background:transparent !important" class="jumbotron jumbotron-fluid text-center vertical-center">
      <div class="container">
        <h1 style="color:white;"> Bienvenido {{ request.user.username }} </h1>

        <div class="sexy_line white"></div>

        <p class="lead">
          App Autenticacion
        </p>

        <div class="lead">
          {% block content %}{% endblock %}
        </div>

      </div>
    </div>

    
    <div class="row" style="margin-top:2%; padding-bottom:2%; background-color:transparent">
      <div class="col-xs-6 col-xs-offset-3 vertical-align">
        Javier Valero | 2018
      </div>
    </div>
  </div>

  <script src="https://use.fontawesome.com/b6810e5c11.js"></script>
  <script src="//code.jquery.com/jquery-1.11.0.min.js"></script>
  <script src="https://netdna.bootstrapcdn.com/bootstrap/3.1.1/js/bootstrap.min.js"></script>

</body>
</html>